# Generated by Django 5.0.7 on 2026-06-22 14:57

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newslettersubscription_pageview_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('youtube', 'YouTube')], max_length=20)),
                ('display_name', models.CharField(max_length=140)),
                ('profile_url', models.URLField()),
                ('username', models.CharField(blank=True, max_length=140)),
                ('headline', models.CharField(blank=True, max_length=220)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('public_items', models.PositiveIntegerField(default=0, help_text='Repos for GitHub, videos for YouTube.')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('embed_url', models.URLField(blank=True, help_text='Optional YouTube channel or featured playlist embed URL.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['platform', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('quote', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/', validators=[core.validators.validate_image_file])),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('event_date', models.DateField()),
                ('category', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('link', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
