# Generated by Django 5.0.7 on 2026-06-24 16:28

from django.db import migrations, models


def seed_deployment_entries(apps, schema_editor):
    DeploymentEntry = apps.get_model("core", "DeploymentEntry")
    entries = [
        ("architecture", "Backend", "Django with SQLite development and PostgreSQL-ready DATABASE_URL.", "bi-database", 10),
        ("architecture", "Frontend", "Bootstrap 5, custom CSS, JavaScript animations, responsive templates.", "bi-window", 20),
        ("architecture", "Content", "Django Admin manages projects, findings, blogs, gallery, videos, certificates, skills, comments, testimonials, and timeline.", "bi-kanban", 30),
        ("architecture", "Security", "CSRF protection, upload validators, environment secrets, secure-cookie production switches, and custom errors.", "bi-shield-lock", 40),
        ("architecture", "Media", "Cloudinary-ready media storage for uploaded images, documents, certificates, and resume files.", "bi-cloud-upload", 50),
        ("architecture", "Deployment", "WhiteNoise static files, Gunicorn, PostgreSQL driver, HTTPS/HSTS environment controls, and Render hosting.", "bi-rocket-takeoff", 60),
        ("checklist", "Production readiness", "Set a strong SECRET_KEY, configure ALLOWED_HOSTS and CSRF_TRUSTED_ORIGINS, connect Neon through DATABASE_URL, run migrations, collect static files, and keep media in Cloudinary.", "bi-check2-circle", 10),
        ("target", "Supported platforms", "The project is ready to adapt for Render, Koyeb, PythonAnywhere, VPS hosting, or any platform that supports Django, Gunicorn, PostgreSQL, environment variables, and static file serving.", "bi-hdd-network", 10),
    ]
    for section, title, description, icon, sort_order in entries:
        DeploymentEntry.objects.update_or_create(
            section=section,
            title=title,
            defaults={
                "description": description,
                "icon": icon,
                "sort_order": sort_order,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_externalprofile_testimonial_timelineevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('architecture', 'Architecture Card'), ('checklist', 'Production Checklist'), ('target', 'Deployment Target')], default='architecture', max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Optional Bootstrap Icon class, e.g. bi-cloud-check.', max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Deployment entries',
                'ordering': ['section', 'sort_order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Raphael Tibil Punobyin', max_length=160),
        ),
        migrations.AlterField(
            model_name='profile',
            name='professional_title',
            field=models.CharField(default='BSc. Computer Science Student | AWS Certified Cloud Practitioner | Cybersecurity Enthusiast | Python Developer', max_length=180),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(default='I am a BSc. Computer Science student at the University of Energy and Natural Resources with a strong passion for technology, Python backend development, networking, cybersecurity, online instruction, graphic design, and video editing.'),
        ),
        migrations.RunPython(seed_deployment_entries, migrations.RunPython.noop),
    ]
