# Generated by Django 5.0.7 on 2026-06-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_facebook_profile_instagram_profile_snapchat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
