# Generated by Django 5.0.7 on 2026-06-25 01:09

from django.db import migrations
from urllib.parse import parse_qs, urlparse


def normalize_youtube_embed_url(url):
    if not url:
        return url
    parsed = urlparse(url.strip())
    host = parsed.netloc.lower().replace("www.", "").replace("m.", "")
    path_parts = [part for part in parsed.path.split("/") if part]
    query = parse_qs(parsed.query)

    if "youtube-nocookie.com" in host and path_parts[:1] == ["embed"]:
        return url.strip()

    if "youtu.be" in host and path_parts:
        return f"https://www.youtube.com/embed/{path_parts[0]}"

    if "youtube.com" not in host:
        return url.strip()

    if path_parts[:1] == ["embed"] and len(path_parts) > 1:
        return f"https://www.youtube.com/embed/{path_parts[1]}"

    if path_parts[:1] in (["shorts"], ["live"]) and len(path_parts) > 1:
        return f"https://www.youtube.com/embed/{path_parts[1]}"

    video_id = query.get("v", [""])[0]
    if video_id:
        return f"https://www.youtube.com/embed/{video_id}"

    playlist_id = query.get("list", [""])[0]
    if playlist_id:
        return f"https://www.youtube.com/embed/videoseries?list={playlist_id}"

    return url.strip()


def normalize_existing_urls(apps, schema_editor):
    Video = apps.get_model("core", "Video")
    ExternalProfile = apps.get_model("core", "ExternalProfile")

    for video in Video.objects.exclude(youtube_embed_url=""):
        normalized = normalize_youtube_embed_url(video.youtube_embed_url)
        if normalized != video.youtube_embed_url:
            video.youtube_embed_url = normalized
            video.save(update_fields=["youtube_embed_url"])

    youtube_profiles = ExternalProfile.objects.filter(platform="youtube").exclude(embed_url="")
    for profile in youtube_profiles:
        normalized = normalize_youtube_embed_url(profile.embed_url)
        if normalized != profile.embed_url:
            profile.embed_url = normalized
            profile.save(update_fields=["embed_url"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_youtube'),
    ]

    operations = [
        migrations.RunPython(normalize_existing_urls, migrations.RunPython.noop),
    ]
