# Generated by Django 5.0.7 on 2026-06-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_normalize_youtube_embed_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('public_chat', 'Public Chat'), ('admin_assistant', 'Admin Assistant'), ('smart_search', 'Smart Search'), ('contact_assistant', 'Contact Assistant'), ('content_summary', 'Content Summary')], max_length=40)),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('auto', 'Auto'), ('groq', 'Groq'), ('gemini', 'Gemini'), ('local', 'Local fallback')], default='auto', max_length=20)),
                ('assistant_name', models.CharField(default='TIPKODES AI Assistant', max_length=80)),
                ('welcome_message', models.CharField(default='Ask me about Raphael, projects, cybersecurity findings, Python, cloud, videos, certificates, or how to connect.', max_length=240)),
                ('system_prompt', models.TextField(default='You are TIPKODES AI Assistant. Answer from the provided TIPKODES TECH LAB context. Be helpful, concise, honest, and direct users to the contact page when needed.')),
                ('groq_model', models.CharField(default='llama-3.1-8b-instant', max_length=80)),
                ('gemini_model', models.CharField(default='gemini-1.5-flash', max_length=80)),
                ('max_context_items', models.PositiveIntegerField(default=18)),
            ],
            options={
                'verbose_name': 'AI settings',
                'verbose_name_plural': 'AI settings',
            },
        ),
    ]
