# Generated by Django 5.0.7 on 2026-06-25 11:13

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aiinteraction_aisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='ai_key_takeaways',
            field=models.TextField(blank=True, help_text='One takeaway per line.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='blogs/seo/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
